src/fact/urls.py
from django.urls import path, include

from .views import (
    FactListView,
    FactCreateView,
    FactDetailView,
    FactSettingsView,
    FactUpdateView,
    FactDeleteView,
)

app_name = "fact"

urlpatterns = [
    path("", FactListView.as_view(), name="list"),
    path("create/", FactCreateView.as_view(), name="create"),
    path(
        "<slug:fact_slug>/",
        include(
            [
                path("", FactDetailView.as_view(), name="detail"),
                path(
                    "settings/",
                    include(
                        [
                            path("", FactSettingsView.as_view(), name="settings"),
                            path("update/", FactUpdateView.as_view(), name="update"),
                            path("delete/", FactDeleteView.as_view(), name="delete"),
                        ]
                    ),
                    kwargs={"settings_view": True},
                ),
            ]
        ),
    ),
]

src/socialrating/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
import allauth.account.views

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "accounts/signup/",
        allauth.account.views.signup,
        name="account_signup",
        kwargs={"breadcrumb_title": "Sign Up"},
    ),
    path(
        "accounts/login/",
        allauth.account.views.login,
        name="account_login",
        kwargs={"breadcrumb_title": "Sign In"},
    ),
    path("accounts/", include("allauth.urls")),
    path("", TemplateView.as_view(template_name="frontpage.html"), name="frontpage"),
    path("teams/", include("team.urls", namespace="team")),
]

src/team/urls.py
from django.urls import path, include

from .views import (
    TeamListView,
    TeamCreateView,
    TeamDetailView,
    TeamSettingsView,
    TeamUpdateView,
    TeamDeleteView,
    TeamMemberView,
)

app_name = "team"

urlpatterns = [
    path("", TeamListView.as_view(), name="list"),
    path("create/", TeamCreateView.as_view(), name="create"),
    path(
        "<slug:team_slug>/",
        include(
            [
                path("", TeamDetailView.as_view(), name="detail"),
                path(
                    "settings/",
                    include(
                        [
                            path("", TeamSettingsView.as_view(), name="settings"),
                            path("update/", TeamUpdateView.as_view(), name="update"),
                            path("delete/", TeamDeleteView.as_view(), name="delete"),
                            path("members/", TeamMemberView.as_view(), name="members"),
                        ]
                    ),
                    kwargs={"settings_view": True},
                ),
                path("categories/", include("category.urls", namespace="category")),
                path("contexts/", include("context.urls", namespace="context")),
                path("forums/", include("forum.urls", namespace="forum")),
            ]
        ),
    ),
]

src/team/models.py
import logging

from django.db import models
from django.urls import reverse_lazy
from django.contrib.auth.models import Group
from guardian.shortcuts import assign_perm

from utils.models import UUIDBaseModel
from actor.models import Actor

logger = logging.getLogger("socialrating.%s" % __name__)


class Team(UUIDBaseModel):
    """
    Everything belongs to a Team
    """

    class Meta(UUIDBaseModel.Meta):
        ordering = ["name"]
        permissions = (
            ("add_category", "Add Category belonging to this Team"),
            ("add_context", "Add Context belonging to this Team"),
            ("add_forum", "Add Forum belonging to this Team"),
        )

    group = models.OneToOneField(
        Group,
        help_text="The Django Group for all members of this Team",
        on_delete=models.PROTECT,
        related_name="team",
    )

    admingroup = models.OneToOneField(
        Group,
        help_text="The Django Group for admin members of this Team",
        on_delete=models.PROTECT,
        related_name="adminteam",
    )

    name = models.CharField(
        max_length=128, help_text="The name of the Team. Make it short and memorable."
    )

    description = models.TextField(help_text="A short description of this team.")

    slug = models.SlugField(unique=True, help_text="The slug for this Team")

    founder = models.ForeignKey(
        "actor.Actor",
        related_name="founded_teams",
        on_delete=models.PROTECT,
        help_text="The founder of this Team",
    )

    members = models.ManyToManyField(
        "actor.Actor",
        through="team.Membership",
        related_name="teams",
        help_text="The current members of this Team",
    )

    breadcrumb_list_name = "Teams"

    def __str__(self):
        return self.name

    @property
    def detail_url_kwargs(self):
        return {"team_slug": self.slug}

    object_url_namespace = "team"

    def get_absolute_url(self):
        return reverse_lazy(
            self.object_url_namespace + ":detail", kwargs=self.detail_url_kwargs
        )

    def grant_permissions(self):
        """
        - All team members may view the Team
        - Admins may change the Team
        - Admins may delete the Team
        - Admins may create a new Category
        - Admins may create a new Context
        """
        assign_perm("team.view_team", self.group, self)
        assign_perm("team.change_team", self.admingroup, self)
        assign_perm("team.delete_team", self.admingroup, self)
        assign_perm("team.add_category", self.admingroup, self)
        assign_perm("team.add_context", self.admingroup, self)

    def create_django_groups(self):
        # create group
        self.group = Group.objects.create(name=self.name)
        # create admingroup
        self.admingroup = Group.objects.create(name=self.name + " Admins")

    def add_founder_membership(self):
        # add founder as an admin team member
        Membership.objects.create(actor=self.founder, team=self, admin=True)

    def save(self, **kwargs):
        """
        If this is a new Team we have some stuff to do before and after saving
        """
        if self._state.adding:
            # we are creating a new team
            adding = True
            # create django groups as needed before saving
            self.create_django_groups()
        else:
            # we are editing an existing team
            adding = False
        # save team
        super().save(**kwargs)
        # is this a new team?
        if adding:
            # this is a new team, add founder as member
            self.add_founder_membership()
            # and grant Team permissions
            self.grant_permissions()

    @property
    def adminmembers(self):
        return Actor.objects.filter(memberships__team=self, memberships__admin=True)

    @property
    def items(self):
        """
        Return a queryset of all Items belonging to this Team
        """
        from item.models import Item

        return Item.objects.filter(category__team=self)

    @property
    def reviews(self):
        """
        Return a queryset of all Reviews belonging to this Team
        """
        from review.models import Review

        return Review.objects.filter(item__category__team=self)

    @property
    def attachments(self):
        """
        Return a queryset of all Attachments belonging to this Team
        """
        from attachment.models import Attachment

        return Attachment.objects.filter(review__item__category__team=self)

    @property
    def facts(self):
        """
        Return a queryset of all Facts belonging to this team.
        """
        from fact.models import Fact

        return Fact.objects.filter(category__team=self)

    @property
    def ratings(self):
        """
        Return a queryset of all Ratings belonging to this team.
        """
        from rating.models import Rating

        return Rating.objects.filter(category__team=self)

    @property
    def votes(self):
        """
        Return a queryset of all Votes belonging to this team.
        """
        from vote.models import Vote

        return Vote.objects.filter(rating__category__team=self)


class Membership(UUIDBaseModel):
    """
    The m2m through model which links Actor and Team together
    """

    class Meta(UUIDBaseModel.Meta):
        unique_together = [("actor", "team")]

    actor = models.ForeignKey(
        "actor.Actor",
        on_delete=models.PROTECT,
        help_text="The Actor to which this Membership belongs",
        related_name="memberships",
    )

    team = models.ForeignKey(
        "team.Team",
        on_delete=models.CASCADE,
        help_text="The Group to which this Membership belongs",
        related_name="memberships",
    )

    admin = models.BooleanField(
        default=False, help_text="This member is an admin of this Team"
    )

    def __str__(self):
        return "%s is %s of team %s" % (
            self.actor.user.username,
            "an admin" if self.admin else "a member",
            self.team.name,
        )

    def fix_group_memberships(self):
        """
        Fix Django group memberships based on this group membership
        """
        if not self.actor.user.groups.filter(name=self.team.group.name).exists():
            self.actor.user.groups.add(self.team.group)

        if (
            self.admin
            and not self.actor.user.groups.filter(
                name=self.team.admingroup.name
            ).exists()
        ):
            self.actor.user.groups.add(self.team.admingroup)

    def save(self, **kwargs):
        """
        Create Django group memberships to match this Team membership
        """
        super().save(**kwargs)
        self.fix_group_memberships()

src/team/views.py
import logging

from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.shortcuts import redirect, reverse

from guardian.mixins import PermissionListMixin
from utils.mixins import SRViewMixin

from .models import Team

logger = logging.getLogger("socialrating.%s" % __name__)


class TeamCreateView(LoginRequiredMixin, CreateView):
    """
    The TeamCreateView requires no special permissions.
    """

    model = Team
    template_name = "team_form.html"
    fields = ["name", "description"]

    def setup(self, *args, **kwargs):
        super().setup(*args, **kwargs)
        # the TeamCreateView has no mixin to set breadcrumbs so we set it manually
        self.breadcrumbs = [("Teams", reverse("team:list"))]
        self.breadcrumbs.append(("Create", self.request.path))

    def form_valid(self, form):
        """
        Set the current user as team founder of the new team
        """
        # save team including founder
        team = form.save(commit=False)
        team.founder = self.request.user.actor
        team.save()
        messages.success(self.request, "New team created!")
        return redirect(reverse("team:detail", kwargs={"team_slug": team.slug}))


class TeamListView(LoginRequiredMixin, PermissionListMixin, ListView):
    """
    The TeamListView lists the teams which the current user has permissions to see.
    Does not use the SRViewMixin
    """

    model = Team
    paginate_by = 100
    template_name = "team_list.html"
    permission_required = "team.view_team"

    def setup(self, *args, **kwargs):
        """ the TeamListView has no mixin to set breadcrumbs so we set it manually """
        super().setup(*args, **kwargs)
        self.breadcrumbs = [(self.model.breadcrumb_list_name, self.request.path)]


class TeamDetailView(SRViewMixin, DetailView):
    model = Team
    slug_url_kwarg = "team_slug"
    permission_required = "team.view_team"
    template_name = "team_detail.html"


class TeamSettingsView(SRViewMixin, DetailView):
    model = Team
    slug_url_kwarg = "team_slug"
    permission_required = "team.change_team"
    template_name = "team_settings.html"


class TeamMemberView(SRViewMixin, DetailView):
    model = Team
    template_name = "team_members.html"
    slug_url_kwarg = "team_slug"
    permission_required = "team.view_team"
    breadcrumb_title = "Members"


class TeamUpdateView(SRViewMixin, UpdateView):
    model = Team
    template_name = "team_form.html"
    fields = ["description"]
    slug_url_kwarg = "team_slug"
    permission_required = "team.change_team"

    def form_valid(self, form):
        team = form.save()
        messages.success(self.request, "Team updated!")
        return redirect(reverse("team:detail", kwargs={"team_slug": team.slug}))


class TeamDeleteView(SRViewMixin, DeleteView):
    model = Team
    template_name = "team_delete.html"
    slug_url_kwarg = "team_slug"
    permission_required = "team.delete_team"

    def delete(self, request, *args, **kwargs):
        messages.success(
            self.request,
            "Team has been deleted, along with all Contexts and Categories and Items belonging to it, and their related content.",
        )
        return super().delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse("team:list")

src/team/templates/team_create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<form method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      Create Team
    </button>
  {% endbuttons %}
</form>
{% endblock content %}

src/team/templates/team_delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block team_content %}
<h2>Delete Team <i>{{ object.name }}</i> ?</h2>
<p class="lead">Deleting this Team will also delete all <i>{{ object.name }}</i> Categories, Contexts, Items, and their Reviews, Votes and Attachments!
<form method="post" class="form">
  {% csrf_token %}
  {% buttons %}
    <a href="{% url 'team:settings' team_slug=team.slug %}" class="btn btn-primary"><i class="fas fa-undo"></i> No, Go Back</button></a>
    <button type="submit" class="btn btn-danger"><i class="fas fa-times"></i> Yes, Delete Team</button>
  {% endbuttons %}
</form>
{% endblock team_content %}

src/team/templates/team_detail.html
{% extends 'base.html' %}
{% load get_eav_value %}
{% load guardian_tags %}

{% block team_content %}
<div class="card">
  <div class="card-header">
    <h2>{{ team.name }}
        {% if 'change_team' in team_perms %}
          <a href="{% url 'team:settings' team_slug=team.slug %}" class="btn btn-secondary float-right"><i class="fas fa-cog"></i></a>
        {% endif %}
    </h2>
  </div>
  <div class="card-body">
    <p class="lead">{{ team.description }}</p>
    <p class="lead">{{ team.name }} has {{ team.items.count }} Items across {{ team.categories.count }} Categories with a total of {{ team.reviews.count }} Reviews in {{ team.contexts.count }} Contexts. The {{ team.categories.count }} Categories has {{ team.facts.count }} Facts and {{ team.ratings.count }} Ratings with a total of {{ team.votes.count }} Votes.</p>

    {% if team.reviews.exists %}
    {% get_obj_perms request.user for team.reviews.latest as "review_perms" checker %}
    {% if 'view_review' in review_perms %}
    <h2>Latest Review</h2>
    {% include 'includes/review_card.html' with review=team.reviews.latest %}
    {% endif %}
    {% endif %}

    {% if team.items.exists %}
    {% get_obj_perms request.user for team.items.latest as "item_perms" checker %}
    {% if 'view_item' in item_perms %}
    <h2>Newest Item</h2>
    {% include 'includes/item_card.html' with item=team.items.latest compact=True %}
    {% endif %}
    {% endif %}
  </div>
</div>
{% endblock team_content %}

src/team/templates/team_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<form method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
    {% if object %}
      Update Team
    {% else %}
      Create Team
    {% endif %}
    </button>
  {% endbuttons %}
</form>
{% endblock content %}

src/team/templates/team_list.html
{% extends 'base.html' %}
{% load guardian_tags %}

{% block content %}
{% if team_list %}
<p class="lead">You are a member of the following teams:</p>
 <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Members</th>
        <th>Categories</th>
        <th>Items</th>
        <th>Contexts</th>
        <th>Facts</th>
        <th>Ratings</th>
        <th>Reviews</th>
        <th>Attachments</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
    {% for team in team_list %}
      {% get_obj_perms request.user for team as "team_perms" %}
      <tr>
        <td>{{ team.name }}</td>
        <td>{{ team.description }}</td>
        <td>{{ team.members.count }}</td>
        <td>{{ team.categories.count }}</td>
        <td>{{ team.items.count }}</td>
        <td>{{ team.contexts.count }}</td>
        <td>{{ team.facts.count }}</td>
        <td>{{ team.ratings.count }}</td>
        <td>{{ team.reviews.count }}</td>
        <td>{{ team.attachments.count }}</td>
        <td>
          <div style="white-space: nowrap;" class="btn-group-vertical">
          <a href="{% url 'team:detail' team_slug=team.slug %}" class="btn btn-primary"><i class="fas fa-search"></i> Show</a>
          {% if 'change_team' in team_perms %}
            <a href="{% url 'team:settings' team_slug=team.slug %}" class="btn btn-primary"><i class="fas fa-cog"></i> Settings</a>
          {% endif %}
          {% if 'change_team' in team_perms %}
            <a href="{% url 'team:update' team_slug=team.slug %}" class="btn btn-primary"><i class="fas fa-edit"></i> Update Team</a>
          {% endif %}
          {% if 'delete_team' in team_perms %}
            <a href="{% url 'team:delete' team_slug=team.slug %}" class="btn btn-danger"><i class="fas fa-times"></i> Delete Team</a>
          {% endif %}
          </div>
        </td>
      </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<p class="lead">You are not a member of any teams.</p>
{% endif %}
<a href="{% url 'team:create' %}" class="btn btn-success"><i class="fas fa-plus"></i> Create new Team</a>
{% endblock content %}

src/team/templates/team_members.html
{% extends 'base.html' %}

{% block team_content %}
<h2>Member List for {{ team.name }}</h2>
 <table class="table table-bordered">
    <thead>
      <tr>
        <th>Username</th>
        <th>Name</th>
        <th>Team Role</th>
        <th>Member Actions</th>
      </tr>
    </thead>
    <tbody>
    {% for membership in team.memberships.all %}
      <tr>
        <td>{{ membership.actor.user.username }}</td>
        <td>{{ membership.actor.user.full_name }}</td>
        <td>{% if membership.admin %}Administrator{% else %}Member{% endif %}</td>
        <td>

        </td>
      </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock team_content %}

src/team/templates/team_overview.html
{% extends 'base.html' %}

{% block team_content %}
<p class="lead">Team page for {{ team.name }}</p>
{% endblock team_content %}

src/team/templates/team_settings.html
{% extends 'base.html' %}

{% block team_content %}
<p class="lead">Settings for Team: {{ team.name }}</p>
{% if 'change_team' in team_perms %}
    <a href="{% url 'team:update' team_slug=team.slug %}" class="btn btn-primary"><i class="fas fa-edit"></i> Update Team</a>
{% endif %}
{% if 'delete_team' in team_perms %}
    <a href="{% url 'team:delete' team_slug=team.slug %}" class="btn btn-danger"><i class="fas fa-times"></i> Delete Team</a>
{% endif %}
<hr>
<a class="btn btn-primary" href="{% url 'team:category:list' team_slug=team.slug %}"><i class="fas fa-list"></i> Categories</a>
<a class="btn btn-primary" href="{% url 'team:context:list' team_slug=team.slug %}"><i class="fas fa-list"></i> Contexts</a>
<a class="btn btn-primary" href="{% url 'team:members' team_slug=team.slug %}"><i class="fas fa-list"></i> Members</a>
{% endblock team_content %}